@startuml colaborativadois

interface DeckBuilder<T> {
    + void reset()
    + void shuffle()
    + void createCards()
    + T getDeck() 
}

class Director {
    - deck: Deck
    + Director(deck: Deck)
    + changeDeck(deck: Deck)
    + make(type: DeckType)
}

class TraditionalDeckBuilder {
    + void reset()
    + void shuffle()
    + void createCards()
}

class UnoDeckBuilder {
    + void reset()
    + void shuffle()
    + void createCards()
}

enum DeckType {
    TRADITIONAL
    UNO
}

' Relacionamentos

UnoDeckBuilder ..|> DeckBuilder
TraditionalDeckBuilder ..|> DeckBuilder

Director --> DeckBuilder

@enduml