@startuml diagrama_com_factory

'--------------------- Classes Baralho ---------------------
abstract class Baralho {
    # cartaFactory : CartaFactory
    # numeroDeCartas : int
    # faces : String[]
    # cartas: Stack<Carta>

    ~ Baralho()
    ~ Baralho(numeroDeCartas : int, faces : String[], cartas : Stack<Carta>, cartaFactory : CartaFactory)
    + embaralhar() : void
    + distribuirCarta() : Carta
    + obterTamanho() : int
    + temCarta() : boolean
    + adicionarCarta(carta: Carta) : void
    + toString() : String
}

' extends Baralho
class BaralhoTradicional extends Baralho {
    - NUMERO_DE_CARTAS_POR_NAIPE : int = 3 {readOnly}

    + BaralhoTradicional()
    + BaralhoTradicional(numeroDeCartas : int, faces : String[], Stack<Carta> cartas)
    + getNumeroDeCartasPorNaipe() : int
}

' extends Baralho
class BaralhoUNO extends Baralho {
    + BaralhoUNO()
}

'--------------------- Classes Carta ---------------------

abstract class Carta {
    # face : String
    # cores : List<Cor>
    # valor : int

    + Carta(face: String, cores : List<Cor>, valor : int)
    + Carta(face : String, cor : Cor, valor : int)
    + getFace() : String
    + setFace() : String
    + getCores() : List<Cor>
    + setCores(cores : Cor...)
    + getCor() : Cor
    + getValor() : int
    + setValor(valor : int) : void
    + {abstract} setNaipe(Naipe naipe) : void
    + {abstract} setAcoes(acoes : String...)
    + {abstract} getNaipe() : Naipe
    + {abstract} getAcoes() : String[]
}

class CartaTradicional extends Carta {
    - naipe : Naipe

    + CartaTradicional(face: String, naipe : String, cor : Cor)
    + CartaTradicional()
    + toString() : String
    + getNaipe() : String
    + getAcoes() : String[]
    + setAcoes(acoes : String...) : void
    + setNaipe(naipe : Naipe)
}

class CartaUNO extends Carta {
    - String[] acoes

    + CartaUNO()
    + CartaUNO(face: String, valor: int, cor : Cor)
    + CartaUNO(face: String, valor: int, cores: List<Cor>)
    + getCores() : List<Cor>
    + getNaipe() : Naipe
    + getAcoes() : String[]
    + setNaipe(naipe : Naipe)
    + setAcoes(acoes : String...) : void
    + toString() : String
}

enum TipoBaralho {
    UNO
    TRADICIONAL
}

enum Cor {
    PRETO
    VERMELHO
    AMARELO
    AZUL
    VERDE
    RESET

    - ansiCode : String
    - value : String

    + Cor(ansiCode : String, cor : String)
    + ansiCode() : String
    + getValue() : String
}

'--------------------- Builder Pattern ---------------------

interface BaralhoBuilder {
    ~ redefinir() : void
    ~ definirFabricaDeCartas() : void
    ~ definirFaces() : void
    ~ definirQuantidadeDeCartas() : void
    ~ preencherBaralho() : void
    ~ obterResultado : Baralho
}

' implements BaralhoBuilder
class BaralhoTradicionalBuilder {
    - BaralhoTradicional : BaralhoTradicional
    - cartaFactory : CartaFactory
    - faces : String[]
    - numeroDeCartas : int
    - numeroDeCartasPorNaipe : int

    + BaralhoTradicionalBuilder()
    + redefinir() : void
    + preencherBaralho() : void
    + definirFaces() : void
    + definirQuantidadeDeCartas() : void
    + definirFabricaDeCartas() : void
    + obterResultado() : BaralhoTradicional
}

' implements BaralhoBuilder
class BaralhoUNOBuilder {
    - baralhoUNO : BaralhoUNO
    - cartaFactory : CartaFactory
    - faces : String[]

    + BaralhoUNOBuilder()
    + redefinir() : void
    + definirFabricaDeCartas() : void
    + definirFaces() : void
    + definirQuantidadeDeCartas() : void
    + preencherBaralho() : void
    + obterResultado() : BaralhoUNO
}

class BaralhoDirector {
    - baralhoBuilder : BaralhoBuilder

    + BaralhoDirector(baralhoBuilder : BaralhoBuilder)
    + construirBaralho() : void
}

'--------------------- Factory Method ---------------------

interface CartaFactory {
    ~ criarCarta() : Carta
}

' implements CartaFactory
class CartaTradicionalFactory {
    + criarCarta() : CartaTradicional
}

' implements CartaFactory
class CartaUNOFactory {
    + criarCarta() : CartaUNO
}


'--------------------- Cliente ---------------------

class MainBaralho {
    + {static} main(args : String[]) : void
}

'--------------------- Relacionamentos ---------------------

MainBaralho --> BaralhoDirector
BaralhoDirector --> BaralhoBuilder
BaralhoBuilder --> Baralho

BaralhoTradicional ..|> Baralho
BaralhoUNO ..|> Baralho

BaralhoTradicionalBuilder ..|> BaralhoBuilder
BaralhoUNOBuilder ..|> BaralhoBuilder

CartaTradicionalFactory ..|> CartaFactory
CartaUNOFactory ..|> CartaFactory

CartaFactory --> Carta
CartaFactory --* Baralho
Carta --* Baralho : possui
Carta *-- Cor : possui

BaralhoTradicionalBuilder --> BaralhoTradicional
BaralhoUNOBuilder --> BaralhoUNO



@enduml
